[build]
  publish = "dist/portafolio_1.0_jcv"
  command = "npm run build:netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[plugins]]
  package = "@netlify/angular-runtime"
  [plugins.inputs]
    disabled = true
